# Forked from https://github.com/pubref/rules_protobuf
dist: trusty
language: java

os: linux

before_install:
  - V=0.4.3
  - OS=linux
  - ARCH=x86_64
  - GH_BASE="https://github.com/bazelbuild/bazel/releases/download/$V"
  - GH_ARTIFACT="bazel-$V-installer-$OS-$ARCH.sh"
  - URL="$GH_BASE/$GH_ARTIFACT"
  - echo $URL
  - wget -O install.sh $URL
  - chmod +x install.sh
  - ./install.sh --user
  - rm -f install.sh

script:
  - |
    bazel \
      --output_base=$HOME/.cache/bazel \
      --batch \
      --host_jvm_args=-Xmx500m \
      --host_jvm_args=-Xms500m \
      test \
      --verbose_failures \
      --test_output=errors \
      --test_strategy=standalone \
      --spawn_strategy=standalone \
      --genrule_strategy=standalone \
      --local_resources=400,2,1.0 \
      --worker_verbose \
      --strategy=Javac=worker \
      --strategy=Closure=worker \
      //src/test/... \
      $FLAGS

notifications:
  email: false
